Repository SouJunior/vagas-frontend, pull requests merged in 2022-11, with the labels that each got.

#59 Screen: Add Job
  package.json
  src/App.tsx
  src/assets/imgs/logo-name-empresa.svg
  src/components/Header.tsx
  src/components/JobCard/index.tsx
  src/components/JobCard/styles.ts
  src/pages/InsertJobs.tsx
  yarn.lock
Labels: feature

#68 Component: renomear ExtendedFooter.tsx
  src/components/Footer.tsx
  src/components/Layout.tsx
  src/components/SimpleFooter.tsx
  src/pages/Report.tsx
Labels: improvement, code fix

#63 Component: Select
  src/components/Select.tsx
Labels: feature

#72 Config axios api
  package-lock.json
  src/services/api.ts
Labels: feature

#71 Component: Corrigir tamanho (height) do componente (JobCard)
  src/components/JobCard/index.tsx
  src/components/JobCard/styles.ts
  src/pages/InsertJobs.tsx
Labels: code fix

#73 Hotfix/fix package manager+update readme
  README.md
  package-lock.json
Labels: bug fix, documentation, code fix

#74 Adicionado link ao botão Saiba mais na tela de Login
  src/pages/Login.tsx
Labels: feature
