Repository SouJunior/vagas-frontend, pull requests merged in 2022-10, with the labels that each got.

#48 component extendedfooter created
  package-lock.json
  public/index.html
  src/components/ExtendedFooter.tsx
  src/components/JobCard/index.tsx
  src/components/JobCard/styles.ts
  src/components/Layout.tsx
  tailwind.config.js
Labels: enhancement

#45 Página de Denúncias
  src/App.css
  src/App.tsx
  src/assets/imgs/important_vector.png
  src/assets/imgs/mail.svg
  src/components/styles/Container.styled.ts
  src/pages/Report.tsx
Labels: enhancement

#60 Bugfix/header on report page
  src/pages/Report.tsx
Labels: bug

#52 Atualizar estilos do componente JobCard alinhado ao protótipo
  src/components/JobCard/index.tsx
  src/components/JobCard/styles.ts
  src/pages/InsertJobs.tsx
Labels: fix
